//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEstadiaHot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EstadiaHotEntities : DbContext
    {
        public EstadiaHotEntities()
            : base("name=EstadiaHotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acesso> Acesso { get; set; }
        public virtual DbSet<AcessoTipo> AcessoTipo { get; set; }
        public virtual DbSet<Estado_Quarto> Estado_Quarto { get; set; }
        public virtual DbSet<Hospedagem> Hospedagem { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<Quarto> Quarto { get; set; }
        public virtual DbSet<Quarto_Tipo> Quarto_Tipo { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_AcessoAlterarNomeSenha(Nullable<int> cod_Acesso, string nome_Usuario, string senha_Usuario)
        {
            var cod_AcessoParameter = cod_Acesso.HasValue ?
                new ObjectParameter("Cod_Acesso", cod_Acesso) :
                new ObjectParameter("Cod_Acesso", typeof(int));
    
            var nome_UsuarioParameter = nome_Usuario != null ?
                new ObjectParameter("Nome_Usuario", nome_Usuario) :
                new ObjectParameter("Nome_Usuario", typeof(string));
    
            var senha_UsuarioParameter = senha_Usuario != null ?
                new ObjectParameter("Senha_Usuario", senha_Usuario) :
                new ObjectParameter("Senha_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_AcessoAlterarNomeSenha", cod_AcessoParameter, nome_UsuarioParameter, senha_UsuarioParameter);
        }
    
        public virtual ObjectResult<SP_AcessoLogin_Result> SP_AcessoLogin(string nome_Usuario, string senha_Usuario)
        {
            var nome_UsuarioParameter = nome_Usuario != null ?
                new ObjectParameter("Nome_Usuario", nome_Usuario) :
                new ObjectParameter("Nome_Usuario", typeof(string));
    
            var senha_UsuarioParameter = senha_Usuario != null ?
                new ObjectParameter("Senha_Usuario", senha_Usuario) :
                new ObjectParameter("Senha_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AcessoLogin_Result>("SP_AcessoLogin", nome_UsuarioParameter, senha_UsuarioParameter);
        }
    
        public virtual int SP_HospedagemAlterar(Nullable<int> id_Hospedagem, Nullable<int> id_Cliente, Nullable<int> id_Quarto, Nullable<int> id_Funcionario, Nullable<System.DateTime> data_Entrada, Nullable<System.DateTime> data_Saida)
        {
            var id_HospedagemParameter = id_Hospedagem.HasValue ?
                new ObjectParameter("Id_Hospedagem", id_Hospedagem) :
                new ObjectParameter("Id_Hospedagem", typeof(int));
    
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("Id_Cliente", id_Cliente) :
                new ObjectParameter("Id_Cliente", typeof(int));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            var data_SaidaParameter = data_Saida.HasValue ?
                new ObjectParameter("Data_Saida", data_Saida) :
                new ObjectParameter("Data_Saida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HospedagemAlterar", id_HospedagemParameter, id_ClienteParameter, id_QuartoParameter, id_FuncionarioParameter, data_EntradaParameter, data_SaidaParameter);
        }
    
        public virtual int SP_HospedagemCheckOut(Nullable<int> id_Hospedagem, Nullable<int> id_Funcionario, Nullable<decimal> total_Pago)
        {
            var id_HospedagemParameter = id_Hospedagem.HasValue ?
                new ObjectParameter("Id_Hospedagem", id_Hospedagem) :
                new ObjectParameter("Id_Hospedagem", typeof(int));
    
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            var total_PagoParameter = total_Pago.HasValue ?
                new ObjectParameter("Total_Pago", total_Pago) :
                new ObjectParameter("Total_Pago", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HospedagemCheckOut", id_HospedagemParameter, id_FuncionarioParameter, total_PagoParameter);
        }
    
        public virtual int SP_HospedagemClienteInserir(string nome_Cliente, Nullable<bool> sexo, string n_BI, Nullable<System.DateTime> data_Nascimento, string telefone, Nullable<int> id_Quarto, Nullable<int> id_Funcionario, Nullable<System.DateTime> data_Entrada, Nullable<System.DateTime> data_Saida)
        {
            var nome_ClienteParameter = nome_Cliente != null ?
                new ObjectParameter("Nome_Cliente", nome_Cliente) :
                new ObjectParameter("Nome_Cliente", typeof(string));
    
            var sexoParameter = sexo.HasValue ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(bool));
    
            var n_BIParameter = n_BI != null ?
                new ObjectParameter("N_BI", n_BI) :
                new ObjectParameter("N_BI", typeof(string));
    
            var data_NascimentoParameter = data_Nascimento.HasValue ?
                new ObjectParameter("Data_Nascimento", data_Nascimento) :
                new ObjectParameter("Data_Nascimento", typeof(System.DateTime));
    
            var telefoneParameter = telefone != null ?
                new ObjectParameter("Telefone", telefone) :
                new ObjectParameter("Telefone", typeof(string));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            var data_SaidaParameter = data_Saida.HasValue ?
                new ObjectParameter("Data_Saida", data_Saida) :
                new ObjectParameter("Data_Saida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HospedagemClienteInserir", nome_ClienteParameter, sexoParameter, n_BIParameter, data_NascimentoParameter, telefoneParameter, id_QuartoParameter, id_FuncionarioParameter, data_EntradaParameter, data_SaidaParameter);
        }
    
        public virtual int SP_HospedagemInserir(Nullable<int> id_Reserva, Nullable<int> acesso_ID, Nullable<System.DateTime> data_CheckIn, Nullable<System.DateTime> data_CheckOut)
        {
            var id_ReservaParameter = id_Reserva.HasValue ?
                new ObjectParameter("Id_Reserva", id_Reserva) :
                new ObjectParameter("Id_Reserva", typeof(int));
    
            var acesso_IDParameter = acesso_ID.HasValue ?
                new ObjectParameter("Acesso_ID", acesso_ID) :
                new ObjectParameter("Acesso_ID", typeof(int));
    
            var data_CheckInParameter = data_CheckIn.HasValue ?
                new ObjectParameter("Data_CheckIn", data_CheckIn) :
                new ObjectParameter("Data_CheckIn", typeof(System.DateTime));
    
            var data_CheckOutParameter = data_CheckOut.HasValue ?
                new ObjectParameter("Data_CheckOut", data_CheckOut) :
                new ObjectParameter("Data_CheckOut", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HospedagemInserir", id_ReservaParameter, acesso_IDParameter, data_CheckInParameter, data_CheckOutParameter);
        }
    
        public virtual int SP_HospedagemLocalizar(string nome_Cliente)
        {
            var nome_ClienteParameter = nome_Cliente != null ?
                new ObjectParameter("Nome_Cliente", nome_Cliente) :
                new ObjectParameter("Nome_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HospedagemLocalizar", nome_ClienteParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_Quarto_Tipo_PrecoLocalizar(Nullable<int> id_Quarto_Tipo)
        {
            var id_Quarto_TipoParameter = id_Quarto_Tipo.HasValue ?
                new ObjectParameter("Id_Quarto_Tipo", id_Quarto_Tipo) :
                new ObjectParameter("Id_Quarto_Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_Quarto_Tipo_PrecoLocalizar", id_Quarto_TipoParameter);
        }
    
        public virtual ObjectResult<string> SP_Quarto_TipoAlterar(Nullable<int> id_Quarto_Tipo, string quarto_Tipo_Descricao, Nullable<decimal> valor_Tipo_Quarto)
        {
            var id_Quarto_TipoParameter = id_Quarto_Tipo.HasValue ?
                new ObjectParameter("Id_Quarto_Tipo", id_Quarto_Tipo) :
                new ObjectParameter("Id_Quarto_Tipo", typeof(int));
    
            var quarto_Tipo_DescricaoParameter = quarto_Tipo_Descricao != null ?
                new ObjectParameter("Quarto_Tipo_Descricao", quarto_Tipo_Descricao) :
                new ObjectParameter("Quarto_Tipo_Descricao", typeof(string));
    
            var valor_Tipo_QuartoParameter = valor_Tipo_Quarto.HasValue ?
                new ObjectParameter("Valor_Tipo_Quarto", valor_Tipo_Quarto) :
                new ObjectParameter("Valor_Tipo_Quarto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Quarto_TipoAlterar", id_Quarto_TipoParameter, quarto_Tipo_DescricaoParameter, valor_Tipo_QuartoParameter);
        }
    
        public virtual ObjectResult<string> SP_Quarto_TipoInserir(string quarto_Tipo_Descricao, Nullable<decimal> valor_Tipo_Quarto)
        {
            var quarto_Tipo_DescricaoParameter = quarto_Tipo_Descricao != null ?
                new ObjectParameter("Quarto_Tipo_Descricao", quarto_Tipo_Descricao) :
                new ObjectParameter("Quarto_Tipo_Descricao", typeof(string));
    
            var valor_Tipo_QuartoParameter = valor_Tipo_Quarto.HasValue ?
                new ObjectParameter("Valor_Tipo_Quarto", valor_Tipo_Quarto) :
                new ObjectParameter("Valor_Tipo_Quarto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Quarto_TipoInserir", quarto_Tipo_DescricaoParameter, valor_Tipo_QuartoParameter);
        }
    
        public virtual ObjectResult<SP_Quarto_TipoLocalizar_Result> SP_Quarto_TipoLocalizar(string quarto_Tipo_Descricao)
        {
            var quarto_Tipo_DescricaoParameter = quarto_Tipo_Descricao != null ?
                new ObjectParameter("Quarto_Tipo_Descricao", quarto_Tipo_Descricao) :
                new ObjectParameter("Quarto_Tipo_Descricao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Quarto_TipoLocalizar_Result>("SP_Quarto_TipoLocalizar", quarto_Tipo_DescricaoParameter);
        }
    
        public virtual int SP_QuartoAlterar(Nullable<int> id_Quarto, Nullable<int> id_Andar, Nullable<int> id_Quarto_Tipo, Nullable<int> id_Estado_Quarto)
        {
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var id_AndarParameter = id_Andar.HasValue ?
                new ObjectParameter("Id_Andar", id_Andar) :
                new ObjectParameter("Id_Andar", typeof(int));
    
            var id_Quarto_TipoParameter = id_Quarto_Tipo.HasValue ?
                new ObjectParameter("Id_Quarto_Tipo", id_Quarto_Tipo) :
                new ObjectParameter("Id_Quarto_Tipo", typeof(int));
    
            var id_Estado_QuartoParameter = id_Estado_Quarto.HasValue ?
                new ObjectParameter("Id_Estado_Quarto", id_Estado_Quarto) :
                new ObjectParameter("Id_Estado_Quarto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QuartoAlterar", id_QuartoParameter, id_AndarParameter, id_Quarto_TipoParameter, id_Estado_QuartoParameter);
        }
    
        public virtual int SP_QuartoEstadoLocalizar(string quarto)
        {
            var quartoParameter = quarto != null ?
                new ObjectParameter("Quarto", quarto) :
                new ObjectParameter("Quarto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QuartoEstadoLocalizar", quartoParameter);
        }
    
        public virtual int SP_QuartoInserir(Nullable<int> id_Andar, Nullable<int> id_Quarto_Tipo)
        {
            var id_AndarParameter = id_Andar.HasValue ?
                new ObjectParameter("Id_Andar", id_Andar) :
                new ObjectParameter("Id_Andar", typeof(int));
    
            var id_Quarto_TipoParameter = id_Quarto_Tipo.HasValue ?
                new ObjectParameter("Id_Quarto_Tipo", id_Quarto_Tipo) :
                new ObjectParameter("Id_Quarto_Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QuartoInserir", id_AndarParameter, id_Quarto_TipoParameter);
        }
    
        public virtual int SP_QuartoLocalizar(string quarto)
        {
            var quartoParameter = quarto != null ?
                new ObjectParameter("Quarto", quarto) :
                new ObjectParameter("Quarto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QuartoLocalizar", quartoParameter);
        }
    
        public virtual ObjectResult<string> SP_ReservaAlterar(Nullable<int> id_Reserva, Nullable<int> id_Cliente, Nullable<int> id_Quarto, Nullable<System.DateTime> data_Entrada)
        {
            var id_ReservaParameter = id_Reserva.HasValue ?
                new ObjectParameter("Id_Reserva", id_Reserva) :
                new ObjectParameter("Id_Reserva", typeof(int));
    
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("Id_Cliente", id_Cliente) :
                new ObjectParameter("Id_Cliente", typeof(int));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ReservaAlterar", id_ReservaParameter, id_ClienteParameter, id_QuartoParameter, data_EntradaParameter);
        }
    
        public virtual ObjectResult<string> SP_ReservaInserir(Nullable<int> id_Cliente, Nullable<int> id_Quarto, Nullable<System.DateTime> data_Entrada)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("Id_Cliente", id_Cliente) :
                new ObjectParameter("Id_Cliente", typeof(int));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ReservaInserir", id_ClienteParameter, id_QuartoParameter, data_EntradaParameter);
        }
    
        public virtual int SP_ReservaLocalizar(string nome_Cliente)
        {
            var nome_ClienteParameter = nome_Cliente != null ?
                new ObjectParameter("Nome_Cliente", nome_Cliente) :
                new ObjectParameter("Nome_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ReservaLocalizar", nome_ClienteParameter);
        }
    
        public virtual ObjectResult<Reserva> ReservaInserir(Nullable<int> id_Cliente, Nullable<int> id_Quarto, Nullable<System.DateTime> data_Entrada)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("Id_Cliente", id_Cliente) :
                new ObjectParameter("Id_Cliente", typeof(int));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reserva>("ReservaInserir", id_ClienteParameter, id_QuartoParameter, data_EntradaParameter);
        }
    
        public virtual ObjectResult<Reserva> ReservaInserir(Nullable<int> id_Cliente, Nullable<int> id_Quarto, Nullable<System.DateTime> data_Entrada, MergeOption mergeOption)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("Id_Cliente", id_Cliente) :
                new ObjectParameter("Id_Cliente", typeof(int));
    
            var id_QuartoParameter = id_Quarto.HasValue ?
                new ObjectParameter("Id_Quarto", id_Quarto) :
                new ObjectParameter("Id_Quarto", typeof(int));
    
            var data_EntradaParameter = data_Entrada.HasValue ?
                new ObjectParameter("Data_Entrada", data_Entrada) :
                new ObjectParameter("Data_Entrada", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reserva>("ReservaInserir", mergeOption, id_ClienteParameter, id_QuartoParameter, data_EntradaParameter);
        }
    }
}
