//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEstadiaHot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int Id_Pagamento { get; set; }
        public int Id_Hospedagem { get; set; }
        public int Id_Funcionario { get; set; }
        public System.DateTime Data_Pagamento { get; set; }
        public decimal Total_Pago { get; set; }
    
        public virtual Acesso Acesso { get; set; }
        public virtual Hospedagem Hospedagem { get; set; }
    }
}
