//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buya.App.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospedagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospedagem()
        {
            this.Pagamento = new HashSet<Pagamento>();
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int Id_Hospedagem { get; set; }
        public int Id_Reserva { get; set; }
        public int Id_Funcionario { get; set; }
        public System.DateTime Data_CheckIn { get; set; }
        public Nullable<System.DateTime> Data_CheckOut { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Reserva Reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
    }
}
