//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buya.App.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id_Pedido { get; set; }
        public int Id_Servico { get; set; }
        public int Id_Hospedagem { get; set; }
        public System.DateTime Data_Pedido { get; set; }
    
        public virtual Hospedagem Hospedagem { get; set; }
        public virtual Servico_Quarto Servico_Quarto { get; set; }
    }
}
